// =============================================================================
//                        !!! DO NOT EDIT THIS FILE !!!
// =============================================================================

#pragma once
#include <string>
#include <vector>

struct Result {
    int edge_index;
    std::vector<std::string> cycle;
};

/// this is the function you need to implement in deadlock_detector.cpp
/// do not edit this signature !!!
Result detect_deadlock(const std::vector<std::string> & edges);