// =============================================================================
//                        !!! DO NOT EDIT THIS FILE !!!
// =============================================================================
#pragma once
#include <vector>

std::vector<long> fat_check(const std::vector<long> & fat);
