/// ============================================================================
/// Written by pfederl@ucalgary.ca in W2021, for CPSC457.
/// ============================================================================
/// DO NOT EDIT THIS FILE. DO NOT SUBMIT THIS FILE FOR GRADING.

#include <cinttypes>
#include <vector>

std::vector<int64_t>
detect_primes(const std::vector<int64_t> & nums, int n_threads);
